import { StackType } from '.'

export const STACK: StackType = {
  Backend: [
    'Action Cable',
    'GraphQL Yoga',
    'JavaScript',
    'JSONB',
    'MongoDB',
    'Node.js',
    'PostgreSQL',
    'Pothos',
    'Prisma',
    'Redis',
    'Ruby',
    'Ruby on Rails',
    'TypeScript',
  ],
  Frontend: [
    'Apollo Client',
    'Bootstrap',
    'CSS3',
    'Emotion',
    'HTML5',
    'i18next',
    'JavaScript',
    'Next.js',
    'PropTypes',
    'React',
    'SCSS',
    'styled-components',
    'TypeScript',
    'Vite',
  ],
  'JS Libraries': [
    '@progress/kendo-react-excel-export',
    '@progress/kendo-react-pdf',
    '@react-pdf/renderer',
    '@xyflow/react',
    'axios',
    'bcrypt',
    'date-fns',
    'esbuild',
    'i18n-iso-countries',
    'lodash',
    'qrcode',
    'react-content-loader',
    'react-cookie',
    'react-datepicker',
    'react-hook-form',
    'react-international-phone',
    'react-media',
    'react-router',
    'react-select',
    'react-virtualized-auto-sizer',
    'react-window',
    'react-window-infinite-loader',
    'use-react-router-breadcrumbs',
    'uuid',
  ],
  DevDependencies: [
    '@babel',
    '@commitlint/config-conventional',
    'tsc-watch',
    '@graphql-codegen',
    'eslint',
    'husky',
    'jest',
    'prettier',
  ],
  DevOps: [
    'Amazon (API Gateway, CloudFront, Cognito, EC2, RDS, Route 53, S3, SES, SNS, SQS, VPC)',
    'AWS (Amplify, Elastic Beanstalk, IAM, Lambda, Organizations, SDK)',
    'Bitbucket',
    'Cloudflare',
    'Docker',
    'Elastic Load Balancing',
    'Git',
    'GitHub',
    'Heroku',
    'Netlify',
    'Nginx',
    'Postman',
  ],
  Protocols: ['GraphQL', 'REST', 'SSE', 'WebSockets'],
  ThirdParty: ['Auth0', 'NCALayer', 'SIGEX', 'Twilio'],
  Design: ['Atlaskit', 'Bootstrap', 'Figma', 'MUI'],
  Analytics: ['Google Analytics', 'Hotjar', 'Mixpanel', 'Sentry'],
  'Project Management': [
    'Confluence',
    'Google Workspace',
    'Smart Commits',
    'Slack',
    'Jira (@, Product Discovery, Service Management)',
  ],
}
