export const SKILLS = [
  'Product Management',
  'Project Management',
  'User Interviews',
  'Market Research',
  'MVP',
  'Negotiotion',
  'Contract Management',
  'Accounting',
  'Tax Filing',
  'Customer Support',
  'System Design',
  'Cloud Infrastructure',
  'Web Analytics',
  'SEO',
  'Product Analytics',
  'Hiring',
  'Training',
]
