export const SKILLS = [
  'User Interviews',
  'Prototyping',
  'MVP',
  'Negotiotions',
  'Contracts',
  'Accounting',
  'Tax Declarations',
  'SEO',
  'Web Analytics',
  'Customer Support',
  'AWS',
  'Product Management',
  'Market Research',
  'Product Analytics',
  'Project Management',
  'Hiring',
  'Training',
]
